name: Deploy front

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build site
    steps:

      - uses: actions/checkout@v3
        name: Checkout

      - name: Installing dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
            server: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            server-dir: /wwwroot/dev/
            local-dir: ./build/
            protocol: ftp
