name: Deploy Pizzaria_Front

on:
  push:
    branches: 
      -develop
  pull_request:
    branches: 
      -develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Instalando dependencias
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm publish
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wwwroot/dev/
        local-dir: ./Pizzaria_back/Pizzaria_back/bin/Release/net6.0/publish/
        protocol: ftp
